services:
  - type: web
    name: naturein-backend
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: naturein-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: naturein.educa,traexn7qb7vl.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://naturein.educa,https://traexn7qb7vl.vercel.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://naturein.educa,https://traexn7qb7vl.vercel.app

databases:
  - name: naturein-db
    plan: starter
    ipAllowList: []
    postgresMajorVersion: 15
